### ISSUE TITLE
爱企查日常任务 CX12011: "点赞观点" 出错

### ISSUE THREAD

**Issue by lxr760** [WindFgg/Scripts#6]
日志如下
开始任务：点赞观点
(node:20009) UnhandledPromiseRejectionWarning: ReferenceError: nid is not defined
    at dotask (/ql/scripts/raw_Scripts_ql_aiqicha.js:188:9)
    at async aqc (/ql/scripts/raw_Scripts_ql_aiqicha.js:223:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20009) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20009) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

试过3个账号  都是如此

**Comment by WindFgg** [comment]
你自己的人问题  请检查网络

**Comment by lxr760** [comment]
> 你自己的人问题 请检查网络

电信 联通网络下均有此问题，另外 telegram也有其他人反馈此问题

**Comment by WindFgg** [comment]
> > 你自己的人问题 请检查网络
> 
> 电信 联通网络下均有此问题，另外 telegram也有其他人反馈此问题

自用的脚本  不保证其他人可用
